# Deployment for React Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toko
  namespace: default
  labels:
    app: toko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toko
  template:
    metadata:
      labels:
        app: toko
    spec:
      containers:
        - name: toko
          image: asia-southeast2-docker.pkg.dev/purwadika-441705/com-fns-wh-app-repository/toko:latest-2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: "https://api.fadellh.com"
          envFrom:
            - configMapRef:
                name: toko-config
---
# Service for React Service
apiVersion: v1
kind: Service
metadata:
  name: toko
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: toko
  ports:
    - name: toko-http
      port: 80
      targetPort: 80

# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: toko-hpa
#   namespace: default
#   labels:
#     app: toko
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: toko
#   minReplicas: 2
#   maxReplicas: 4
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 85

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fadel.lukman.dev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dev-key
    solvers:
      - http01:
          ingress:
            class: nginx

---
# Ingress for All Services
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toko-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "toko.fadellh.com"
      secretName: react-ssl
  rules:
    - host: toko.fadellh.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: toko
                port:
                  number: 80
