name: GKE Deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

env:
  API_BASE_URL: "https://api.fadellh.com"
  GOOGLE_PROJECT: "purwadika-441705"
  TAG: "latest-${{ github.run_number }}"
  ARTIFACT_REGISTRY: "asia-southeast2-docker.pkg.dev"
  ARTIFACT_FOLDER: "com-fns-wh-app-repository"
  APP_NAME: "toko"

jobs:
  build:
    name: Build and Deploy to GKE
    runs-on: [react-runner]
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MSG_SENDER_ID: ${{ secrets.FIREBASE_MSG_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          API_BASE_URL: ${{ env.API_BASE_URL }}
          GMAPS_API_KEY: ${{ secrets.FIREBASE_GMAPS_API_KEYAPP_ID }}

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }} --quiet

      - name: Containerize
        run: |
          docker build -t "${{ env.ARTIFACT_REGISTRY }}/${{ env.GOOGLE_PROJECT }}/${{ env.ARTIFACT_FOLDER }}/${{ env.APP_NAME }}:${{ env.TAG }}" .
          docker push "${{ env.ARTIFACT_REGISTRY }}/${{ env.GOOGLE_PROJECT }}/${{ env.ARTIFACT_FOLDER }}/${{ env.APP_NAME }}:${{ env.TAG }}"

  deploy:
    name: Deploy to GKE
    runs-on: [react-runner]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to GKE
        run: |
          kubectl apply -f infrastructure/kubernetes/application-deployment.yml
